env: "dev"
http_server:
  address: "localhost:8001" # адрес сервера
  timeout: 4s
  idle_timeout: 60s
nats:
  cluster_id: "test-cluster" # имя кластера
  client_id: "client-123" # имя клиента
  url: "nats://localhost:4223" # ссылка для подключения к nats
