env: "dev"
http_server:
  address: "0.0.0.0:8001" # адрес сервера
  timeout: 4s
  idle_timeout: 60s
nats:
  cluster_id: "test-cluster" # имя кластера
  client_id: "client-123" # имя клиента
  url: "nats://nats-streaming:4223" # ссылка для подключения к nats
